// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_9pIs-yejqnH8n6h93D_FGJjjLrH8T48',
    appId: '1:442603200761:web:021b26ab50b6e883758228',
    messagingSenderId: '442603200761',
    projectId: 'unbound-fbla',
    authDomain: 'unbound-fbla.firebaseapp.com',
    storageBucket: 'unbound-fbla.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSEuq6k4gMb960lyqARNaLy2RyBnriRB4',
    appId: '1:442603200761:android:a2c66e0b6da07def758228',
    messagingSenderId: '442603200761',
    projectId: 'unbound-fbla',
    storageBucket: 'unbound-fbla.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5rFa4pE2zt4azFXC_7EnbxD0mpkLYvlc',
    appId: '1:442603200761:ios:60a0288648856a18758228',
    messagingSenderId: '442603200761',
    projectId: 'unbound-fbla',
    storageBucket: 'unbound-fbla.appspot.com',
    iosBundleId: 'com.example.unbound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5rFa4pE2zt4azFXC_7EnbxD0mpkLYvlc',
    appId: '1:442603200761:ios:142f5d396a8fcb98758228',
    messagingSenderId: '442603200761',
    projectId: 'unbound-fbla',
    storageBucket: 'unbound-fbla.appspot.com',
    iosBundleId: 'com.example.unbound.RunnerTests',
  );
}
